spring.application.name=standbase
spring.jpa.hibernate.ddl-auto=validate

# DB Connection Details
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/standbase}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
